/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class binding_java_Graphiti */

#ifndef _Included_binding_java_Graphiti
#define _Included_binding_java_Graphiti
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     binding_java_Graphiti
 * Method:    graphiti_create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_binding_java_Graphiti_graphiti_1create
  (JNIEnv *, jobject);

/*
 * Class:     binding_java_Graphiti
 * Method:    graphiti_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_graphiti_1destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     binding_java_Graphiti
 * Method:    startUpVCP
 * Signature: (JLjava/lang/String;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_binding_java_Graphiti_startUpVCP
  (JNIEnv *, jobject, jlong, jstring, jboolean, jboolean);

/*
 * Class:     binding_java_Graphiti
 * Method:    shutDownVCP
 * Signature: (JZZ)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_shutDownVCP
  (JNIEnv *, jobject, jlong, jboolean, jboolean);

/*
 * Class:     binding_java_Graphiti
 * Method:    index
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_binding_java_Graphiti_index
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     binding_java_Graphiti
 * Method:    setPin
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_setPin
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     binding_java_Graphiti
 * Method:    clearScreen
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_clearScreen
  (JNIEnv *, jobject, jlong);

/*
 * Class:     binding_java_Graphiti
 * Method:    sleep
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_sleep
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     binding_java_Graphiti
 * Method:    getNextOutputEvent
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_binding_java_Graphiti_getNextOutputEvent
  (JNIEnv *, jobject, jlong);

/*
 * Class:     binding_java_Graphiti
 * Method:    getNextGestureEvent
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_binding_java_Graphiti_getNextGestureEvent
  (JNIEnv *, jobject, jlong);

/*
 * Class:     binding_java_Graphiti
 * Method:    getDisplayStatusEvent
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_binding_java_Graphiti_getDisplayStatusEvent
  (JNIEnv *, jobject, jlong);

/*
 * Class:     binding_java_Graphiti
 * Method:    getNextKeyEvent
 * Signature: (J)Ljava/util/Set;
 */
JNIEXPORT jobject JNICALL Java_binding_java_Graphiti_getNextKeyEvent
  (JNIEnv *, jobject, jlong);

/*
 * Class:     binding_java_Graphiti
 * Method:    getNextDrawEvent
 * Signature: (J)Lbinding/java/Graphiti/DrawEvent;
 */
JNIEXPORT jobject JNICALL Java_binding_java_Graphiti_getNextDrawEvent
  (JNIEnv *, jobject, jlong);

/*
 * Class:     binding_java_Graphiti
 * Method:    startResponseThread
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_startResponseThread
  (JNIEnv *, jobject, jlong);

/*
 * Class:     binding_java_Graphiti
 * Method:    stopResponseThread
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_stopResponseThread
  (JNIEnv *, jobject, jlong);

/*
 * Class:     binding_java_Graphiti
 * Method:    sendACK
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_sendACK
  (JNIEnv *, jobject, jlong);

/*
 * Class:     binding_java_Graphiti
 * Method:    sendNACK
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_sendNACK
  (JNIEnv *, jobject, jlong);

/*
 * Class:     binding_java_Graphiti
 * Method:    getSoftwareVersion
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_getSoftwareVersion
  (JNIEnv *, jobject, jlong);

/*
 * Class:     binding_java_Graphiti
 * Method:    getHardwareVersion
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_getHardwareVersion
  (JNIEnv *, jobject, jlong);

/*
 * Class:     binding_java_Graphiti
 * Method:    getSerialNumber
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_getSerialNumber
  (JNIEnv *, jobject, jlong);

/*
 * Class:     binding_java_Graphiti
 * Method:    getBatteryStatus
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_getBatteryStatus
  (JNIEnv *, jobject, jlong);

/*
 * Class:     binding_java_Graphiti
 * Method:    getResolutionInformation
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_getResolutionInformation
  (JNIEnv *, jobject, jlong);

/*
 * Class:     binding_java_Graphiti
 * Method:    getDeviceOrientation
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_getDeviceOrientation
  (JNIEnv *, jobject, jlong);

/*
 * Class:     binding_java_Graphiti
 * Method:    getHeightInformation
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_getHeightInformation
  (JNIEnv *, jobject, jlong);

/*
 * Class:     binding_java_Graphiti
 * Method:    getDeviceName
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_getDeviceName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     binding_java_Graphiti
 * Method:    updateDisplay
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_updateDisplay
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     binding_java_Graphiti
 * Method:    setDisplay
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_setDisplay
  (JNIEnv *, jobject, jlong);

/*
 * Class:     binding_java_Graphiti
 * Method:    clearDisplay
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_clearDisplay
  (JNIEnv *, jobject, jlong);

/*
 * Class:     binding_java_Graphiti
 * Method:    updateSinglePixel
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_updateSinglePixel
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     binding_java_Graphiti
 * Method:    updateSingleRow
 * Signature: (JI[B)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_updateSingleRow
  (JNIEnv *, jobject, jlong, jint, jbyteArray);

/*
 * Class:     binding_java_Graphiti
 * Method:    updateSingleColumn
 * Signature: (JI[B)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_updateSingleColumn
  (JNIEnv *, jobject, jlong, jint, jbyteArray);

/*
 * Class:     binding_java_Graphiti
 * Method:    getAllPixelsPositionStatus
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_getAllPixelsPositionStatus
  (JNIEnv *, jobject, jlong);

/*
 * Class:     binding_java_Graphiti
 * Method:    getSinglePixelPositionStatus
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_getSinglePixelPositionStatus
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     binding_java_Graphiti
 * Method:    getSingleRowPixelPositionStatus
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_getSingleRowPixelPositionStatus
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     binding_java_Graphiti
 * Method:    getSingleColumnPixelPositionStatus
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_getSingleColumnPixelPositionStatus
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     binding_java_Graphiti
 * Method:    showMessage
 * Signature: (JLjava/lang/String;[BI)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_showMessage
  (JNIEnv *, jobject, jlong, jstring, jbyteArray, jint);

/*
 * Class:     binding_java_Graphiti
 * Method:    setCursor
 * Signature: (JIIIII)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_setCursor
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     binding_java_Graphiti
 * Method:    sendImageInterruptible
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_sendImageInterruptible
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     binding_java_Graphiti
 * Method:    sendImageBlocking
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_sendImageBlocking
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     binding_java_Graphiti
 * Method:    setKeyEvent
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_setKeyEvent
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     binding_java_Graphiti
 * Method:    setTouchEvent
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_setTouchEvent
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     binding_java_Graphiti
 * Method:    getLastTouchPointStatus
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_getLastTouchPointStatus
  (JNIEnv *, jobject, jlong);

/*
 * Class:     binding_java_Graphiti
 * Method:    vibratorControlCommand
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_vibratorControlCommand
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     binding_java_Graphiti
 * Method:    getDateAndTime
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_getDateAndTime
  (JNIEnv *, jobject, jlong);

/*
 * Class:     binding_java_Graphiti
 * Method:    setDateAndTime
 * Signature: (JIIIIII)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_setDateAndTime
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
