/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class binding_java_Graphiti */

#ifndef _Included_binding_java_Graphiti
#define _Included_binding_java_Graphiti
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     binding_java_Graphiti
 * Method:    graphiti_create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_binding_java_Graphiti_graphiti_1create
  (JNIEnv *, jobject);

/*
 * Class:     binding_java_Graphiti
 * Method:    graphiti_createWithConnection
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_binding_java_Graphiti_graphiti_1createWithConnection
  (JNIEnv *, jobject, jlong);

/*
 * Class:     binding_java_Graphiti
 * Method:    graphiti_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_graphiti_1destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     binding_java_Graphiti
 * Method:    setConnection
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_setConnection
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     binding_java_Graphiti
 * Method:    startUpVCP
 * Signature: (JLjava/lang/String;ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_binding_java_Graphiti_startUpVCP
  (JNIEnv *, jobject, jlong, jstring, jboolean, jboolean);

/*
 * Class:     binding_java_Graphiti
 * Method:    shutDownVCP
 * Signature: (JZZ)V
 */
JNIEXPORT void JNICALL Java_binding_java_Graphiti_shutDownVCP
  (JNIEnv *, jobject, jlong, jboolean, jboolean);

/*
 * Class:     binding_java_Graphiti
 * Method:    getNextOutputEvent
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_binding_java_Graphiti_getNextOutputEvent
  (JNIEnv *, jobject, jlong);

/*
 * Class:     binding_java_Graphiti
 * Method:    getDisplayStatusEvent
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_binding_java_Graphiti_getDisplayStatusEvent
  (JNIEnv *, jobject, jlong);

/*
 * Class:     binding_java_Graphiti
 * Method:    getNextKeyEvent
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_binding_java_Graphiti_getNextKeyEvent
  (JNIEnv *, jobject, jlong);

/*
 * Class:     binding_java_Graphiti
 * Method:    getNextDrawEvent
 * Signature: (J)Lbinding/java/Graphiti/DrawEvent;
 */
JNIEXPORT jobject JNICALL Java_binding_java_Graphiti_getNextDrawEvent
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
